def project_folder = 'hello-angular-ui'
pipeline {
  agent any

  stages {

    stage('Initialize') {
      steps {
        sh '''          
          echo "PATH = ${PATH}"
          echo "M2_HOME = ${M2_HOME}"                   
          '''
        println "project_folder =  ${project_folder} "
      }
    }

    stage('install dependencies') {
      steps {
        dir(project_folder) {
          script {
            sh "npm install"
          }
        }
      }
    }
    stage('build code') {
      steps {
        dir(project_folder) {
          script {
            sh "npm build"
          }
        }
      }
    }

    stage('push to to S3') {
      steps {
        dir(project_folder) {

          s3Upload(
            // profileName:'Default',
            profileName: 'build',
            dontWaitForConcurrentBuildCompletion: true,
            dontSetBuildResultOnFailure: false,
            consoleLogLevel: 'INFO',
            pluginFailureResultConstraint: 'FAILURE',
            entries: [
              [
                bucket: "equitasit-jenkins-build/${JOB_NAME}-${BUILD_NUMBER}",
                sourceFile: 'dist/*.*',
                selectedRegion: 'us-east-1',
                noUploadOnFailure: true
              ]
            ],
            userMetadata: []

          )

        }
      }
    }

  }
}